full lazy init of HSAContext
RadeonOpenCompute/hcc pull request #1138
Opened 2019-05-02 17:47 UTC by jeffdaily

HSAContext is no longer a module static object to be initialized during C++ static initialization.
HCC_LAZYINIT=ON is now the default behavior.

These changes allow dependent libraries and frameworks to be able to call fork() et al prior to
initializing the underlying HSA and kernel runtimes since HCC intialization is deferred until first use.

2019-05-02 20:17 UTC, scchan reviewed
Would it be sufficient to set this to `false`?  https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/lib/mcwamp.cpp#L411

I had a PR to make that change but reverted it later due to a bug in HIP, which I think has been fixed.

2019-05-02 20:34 UTC, jeffdaily commented
I would have simply set line 411 to false, but I wasn't sure about apps or libraries that might depend on the current default behavior of the immediate (i.e. non-lazy) init.  I reversed all the logic so that users could still access the old behavior by setting HCC_LAZYINIT=ON or HCC_LAZYINIT=0.  (I just pushed a fix for the latter.)

2019-05-02 20:40 UTC, jeffdaily commented
Looks like I misunderstood the C++ static initialization order.   Setting HCC_LAZYINIT=ON was sufficient for full lazy initialization.  Should I revert the changes to the mcwamp_hsa.cpp file but leave the mcwamp.cpp changes?

2019-05-02 20:54 UTC, jeffdaily commented
@scchan Please review again.   The change to enable lazy init by default is now much simpler, and allows users to resume the previous behavior by setting HCC_LAZYINIT=OFF or HCC_LAZYINIT=0.

2019-05-02 21:07 UTC, scchan approved these changes
LGTM

2019-05-03 21:32 UTC, jeffdaily commented
I am looking into the failed tests.  Such as 
```
terminate called after throwing an instance of 'Kalmar::runtime_exception'
  what():  HSA executable NOT built yet!
```

```
Failing Tests (5):
    HCC :: Unit/HC/accelerator_get_all_views_mt.cpp
    HCC :: Unit/HC/memcpy_symbol1.cpp
    HCC :: Unit/HC/memcpy_symbol2.cpp
    HCC :: Unit/HC/memcpy_symbol3.cpp
    HCC :: Unit/HC/memcpy_symbol4.cpp
```

2019-05-06 20:45 UTC, jeffdaily commented
Down to 1 failure.
```

2019-05-06 20:58 UTC, jeffdaily commented
@scchan I expect all tests to pass now.  The final failing tested needed to be updated for the new lazy init default since it changes the number of accelerator views created.

2019-05-06 21:13 UTC, scchan requested changes

2019-05-06 21:13 UTC, scchan commented on lib/hsa/mcwamp_hsa.cpp
> +        if (!executables_loaded) {
I think this is racy and probably needs to be protected by something like `std::call_once` ?

2019-05-08 16:05 UTC, jeffdaily commented
I'm not sure how our CI is set up, but an unrelated commit triggered a rebuild of the PR-1138 jenkins build and it is now failing, even though it was passing on build 7 of this PR.

2019-05-09 22:12 UTC, scchan submitted a review, later dismissed
LGTM in principle but now this PR has a merge conflict with the on-demand signal allocation patch you submitted earlier, could you take a look?

2019-05-10 19:01 UTC, jeffdaily commented
@scchan I don't know that the failed test is due to the PR.  Should we have jenkins retest?  All tests were passing on my local system.

2019-05-10 19:20 UTC, scchan approved these changes
LGTM

2019-05-10 19:20 UTC, merged