do not dlclose; better lazy init of HSA context
RadeonOpenCompute/hcc pull request #1296
Opened 2019-10-31 19:03 UTC by jeffdaily

2019-11-01 03:54 UTC, ssahasra approved these changes
Looks good to me. After this is committed, I will check if I can renable the flush/delete of the printf buffer.

2019-11-01 15:11 UTC, jeffdaily commented
@ssahasra yes thank you.  Though this PR is needed to resolve a seg fault in one of our codes, I was concerned about the moving of the printf block of code.
Is there a corresponding PR for re-enabling printf?  Has it been tested against the previous failure cases (I would need to search our ticketing system)?

2019-11-03 09:18 UTC, ssahasra commented
Printf was re-enabled a few days ago with the following PR:
https://github.com/RadeonOpenCompute/hcc/pull/1290

It's already merged in clang_tot_upgrade.

2019-11-04 15:40 UTC, jeffdaily commented
@ssahasra when I merged this PR with upstream I mistakenly added the printf ifdef back in and I'm assuming that is what broke the few CI tests.  I just pushed the fix; let's see if CI recovers.

2019-11-05 04:01 UTC, ssahasra commented
> 
> 
> @ssahasra when I merged this PR with upstream I mistakenly added the printf ifdef back in and I'm assuming that is what broke the few CI tests. I just pushed the fix; let's see if CI recovers.

Good catch! I confused that macro with the other one "HCC_ENABLE_ACCELERATOR_PRINTF" when reviewing your original patch.

2019-11-12 19:03 UTC, scchan requested changes

2019-11-12 19:03 UTC, scchan commented on lib/hsa/mcwamp_hsa.cpp
> +  delete Kalmar::__ctx;
It seems that `Kalmar::__ctx` should be initialized to `nullptr` and then we should check whether it's still `nullptr` here before deleting it.

2019-11-12 22:15 UTC, scchan approved these changes

2019-11-13 18:25 UTC, merged