clang_tot_upgrade
RadeonOpenCompute/hcc pull request #199
Opened 2016-12-21 18:25 UTC by AlexVlx

Adopt short-form GFX_ip family names in the CMake and Driver infrastructure.

2016-12-21 21:21 UTC, scchan requested changes
Could you rebase your commit since it also includes other commits already in clang_tot_upgrade?

2016-12-21 21:24 UTC, scchan commented on CMakeLists.txt
>      list(APPEND AMDGPU_TARGET_LIST "fiji")
Let's keep the support for the long names for now

2016-12-21 21:25 UTC, scchan commented on CMakeLists.txt
>      list(APPEND AMDGPU_TARGET_LIST "fiji")
Maybe add a warning that the long names are being deprecated?

2016-12-22 00:11 UTC, AlexVlx commented on CMakeLists.txt
>      list(APPEND AMDGPU_TARGET_LIST "fiji")
Excellent idea, I wish I had thought about that before! Please see the updated form and if it fits what you had in mind. It is not necessarily the most efficient way of doing things, but I presume we will remove this sooner as opposed to later. Thank you for the suggestion.

2016-12-22 02:43 UTC, whchung reviewed
We may also need to add "gfx700" into supported list. I removed Kaveri support a while ago, but it seems we still have ROCm users using Kaveri APU for development.

2016-12-22 22:34 UTC, AlexVlx commented
Hello @whchung. Thank you for the reply - isn't Kaveri formally deprecated in the context of ROCm? Which would make enabling it here a bit iffy, unless there's been a recent change in that regard. Having said this, I believe that this argues in favour of a redesign of how we handle this particular aspect (selecting the GFXip family), so that we have a single shared list of enabled IP configurations which drives the decisions everywhere, be it CMake of the Driver. I will not have time to implement that this year, but I think it'd be useful to have overall and we might as well figure out what to do about Kaveri by then. Does that sound reasonable? Thank you. Cheers!

2016-12-23 02:22 UTC, merged

2016-12-23 02:25 UTC, whchung commented
@AlexVlx to my understanding there are still users who use Clang 3.5-based HCC and using `--amdgpu-target=AMD:AMDGPU:7:0:0`, so in order not to bring them unexpected surprises we should still keep this option in Clang 4.0-based HCC. I've merged this PR and will submit commits to address this later on.

2016-12-23 03:21 UTC, whchung commented on lib/clamp-device.in
> +if [ $AMDGPU_TARGET == "gfx701" ]; then
after testing with end-to-end programs, changes in this file are actually incorrect. I've fixed them in further commits.

2016-12-23 07:49 UTC, AlexVlx commented
@whchung thank you for the clarification, that's pretty interesting. Having said that, I recall that we are on record saying that Kaveri support is deprecated. Perhaps we should at least issue a warning to that extent? Otherwise users might have even less pleasant surprises if they actually put a codebase together and an upstream driver change breaks them utterly, which could happen at any point...