added option to rocdl to build hc lib & cleanup
RadeonOpenCompute/hcc pull request #295
Opened 2017-04-20 15:44 UTC by dfukalov

1. added option to rocdl to build hc lib
2. minor cleanup of unused include

2017-04-20 19:45 UTC, dfukalov commented
the option is "on" by default in device library currently, but going to be changed to default value "off" in order to re-enable the library build with LC (not HCC)

2017-04-21 03:57 UTC, whchung requested changes

2017-04-21 03:57 UTC, whchung commented on CMakeLists.txt
> +            -DBUILD_HC_LIB=ON
@dfukalov there is no such flag `BUILD_HC_LIB` inside `ROCm-Device-Libs`, could you explain the rationale behind adding this line?

2017-04-21 04:06 UTC, whchung commented on CMakeLists.txt
> +            -DBUILD_HC_LIB=ON
@dfukalov after checking your earlier comment I think I know the rationale now. I'll hold off this PR and merge it when `ROCm-Device-Libs` does carry this switch.

2017-04-21 04:06 UTC, whchung approved these changes

2017-04-21 12:04 UTC, dfukalov commented on CMakeLists.txt
> +            -DBUILD_HC_LIB=ON
Yes, the switch was added in http://git.amd.com:8080/#/c/82189/ and is not arrived yet.
The will not brake build, however warning of unused variable will be produced.

2017-04-24 10:59 UTC, dfukalov commented
will merge this pull request once library change arrives to hcc tree

2017-04-27 00:02 UTC, merged