Fix finegrain
RadeonOpenCompute/hcc pull request #320
Opened 2017-05-17 22:04 UTC by bensander

Includes a couple bug fixes in fine-grain mem allocations

2017-05-18 01:38 UTC, whchung requested changes
The 2 new global variables shall be better reviewed & re-factored.
- `g_hsaAgents` seems can be abolished.
- `g_agentToDeviceMap` seems can be set as a member variables inside `HSAContext`.

2017-05-18 01:38 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +static std::vector<hsa_agent_t > g_hsaAgents; // Array of the CPU + all GPU agents.
It seems `g_hsaAgents` is never read in any codes. Would future codes need this vector? If not we should consider remove it.

2017-05-18 01:38 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +static std::map<uint64_t, Kalmar::HSADevice *> g_agentToDeviceMap;
Could `g_agentToDeviceMap` be a member variable of `HSAContext`? It can be then queries by `HSADevice` via a member function.

2017-05-18 01:38 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +    static int get_seqnum_from_agent (hsa_agent_t hsaAgent)
This static member function is defined but no one really calls it.

2017-05-18 01:38 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +        g_agentToDeviceMap.insert(std::pair<uint64_t, HSADevice*> (agent.handle, this));
`g_agentToDeviceMap` is populated here, and would be queried by `HSADevice::get_seqnum_from_agent()`. But in the PR there is actually no one calling that static member function, thus making this map unused.

2017-05-18 01:38 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +        g_hsaAgents.push_back(agent);
`g_hsaAgents` is populated here but is never used elsewhere in this PR.

2017-05-18 18:53 UTC, bensander commented on lib/hsa/mcwamp_hsa.cpp
> +        g_agentToDeviceMap.insert(std::pair<uint64_t, HSADevice*> (agent.handle, this));
This is future functionality, will be used for some upcoming debug functionality to translate the hsaAgent handle into a human-readable device#.

2017-05-19 16:07 UTC, bensander commented
Updated pull request to address Jack feeedback

2017-05-19 23:33 UTC, whchung approved these changes

2017-05-19 23:34 UTC, whchung commented
@bensander The PR looks good now. Could you help resolve the merge conflicts so I can take it?

2017-05-19 23:48 UTC, merged