HCC RT Header needs to trigger re-build
RadeonOpenCompute/hcc pull request #358
Opened 2017-06-14 20:23 UTC by aaronenyeshi

This resolves JIRA Ticket SWDEV-123229 - HCC RT header changes don't trigger a re-build.

There was an issue with HCC RT Headers not triggering a re-build when running make. This was due to dependencies not being properly set and checked for headers in hcc/include.

2017-06-14 20:26 UTC, aaronenyeshi commented
I have tested this on unit tests, and there are no new testcase failures with this. With this fix, developers can modify headers such as kalmar_runtime.h and run make which will be triggered from header file changes. 

Please let me know if I should also make this change for files include/coordinate, include/array_view, and subdirectory include/experimental/.

2017-06-14 20:29 UTC, whchung commented
@aaronenyeshi thanks for this PR! please help amend it for other headers within `include` directory. Thanks.

2017-06-14 20:36 UTC, scchan requested changes

2017-06-14 20:36 UTC, scchan commented on include/CMakeLists.txt
> +
is there a way to automatically generate these lists instead of constructing them manually?

2017-06-14 21:01 UTC, aaronenyeshi commented on include/CMakeLists.txt
> +
I will take a look

2017-06-15 02:18 UTC, aaronenyeshi reviewed
Just added another commit to generate the dependency without having to specify each header files explicitly, using regular expressions on the file names.

I still need to add another commit for other header files in the `include `directory.

2017-06-15 15:12 UTC, aaronenyeshi commented
Okay, I've made it generate lists automatically for the header files.
In addition, I've included the other headers inside `include` .
Also, now there is a target for hcc-headers, and pstl-headers.
 
These commits does not produce any new testcase failures. Please take a look. Thanks!

2017-06-15 15:53 UTC, whchung approved these changes
LGTM. @scchan and @pfultz2 ?

2017-06-15 16:28 UTC, scchan commented
looks like the build failed to generate the .deb package.
@aaronenyeshi could you do a "make package" and see if you could reproduce it?

2017-06-15 17:30 UTC, aaronenyeshi commented
Yes, I was able to find the bug, and fix it. Seems it dropped the sub-directory impl/ string in the cmake-install.cmake built file.

2017-06-15 17:48 UTC, aaronenyeshi commented on include/CMakeLists.txt
> +set_target_properties(hcc-headers PROPERTIES FOLDER "HCC Misc")
This line might not be useful, as its meant for MS Visual Studio UI navigation. Should i remove it?

2017-06-15 17:51 UTC, whchung commented on include/CMakeLists.txt
> +set_target_properties(hcc-headers PROPERTIES FOLDER "HCC Misc")
@aaronenyeshi thanks for spotting this. let's remove it for now.

2017-06-15 18:10 UTC, aaronenyeshi commented on include/CMakeLists.txt
> +set_target_properties(hcc-headers PROPERTIES FOLDER "HCC Misc")
Great! I think it is ready to be merged.

2017-06-15 19:55 UTC, scchan approved these changes

2017-06-15 20:04 UTC, merged