Feature hcc profile
RadeonOpenCompute/hcc pull request #362
Opened 2017-06-15 19:23 UTC by bensander

Simple but useful GPU command profiler for HCC.  Enabled with env var, shows kernel and data  xfer times and bandwidth.

2017-06-15 19:55 UTC, aaronenyeshi commented
Hi, is there documentation on these debuggers and profilers? I think it would be very useful to add how to use this tool (such as which env var to set) into debugging documentations.

2017-06-15 20:03 UTC, whchung requested changes

2017-06-15 20:03 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +#define KALMAR_DEBUG (0)
@bensander please help remove this line.

2017-06-15 20:03 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +        //fun = "_ZZN8hip_impl21grid_launch_hip_impl_IZ76Cijk_Alik_Bljk_SB_MT064x128x08_GSU06_MO10_PGR0_PLR0_TT04_08_WG16_16_01_WGM01PfPKfS3_ffjjjjjjjjjjjjjP12ihipStream_tjPP11ihipEvent_tS8_E4$_36JNS
@bensander please help remove this line.

2017-06-15 20:03 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +char * HCC_PROFILE_FILE=nullptr;
@bensander i'm seeing more file-scope global variables growing... how about we move them into `HSAContext`?

2017-06-15 20:03 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +    bool isAsync;;          // copy was performed asynchronously
@bensander double `;` in the code.

2017-06-15 20:03 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> -        Kalmar::ctx.releaseSignal(signal, signalIndex);
@bensander could you provide justification why these 2 lines be removed in this PR? I thought this PR is to add kernel profiling logic. but changing these 2 lines would essentially change the behavior of HSA signal reclaim process. I'm not alluding the code is wrong, but perhaps it should be made in a separate PR?

2017-06-21 03:15 UTC, bensander commented on lib/hsa/mcwamp_hsa.cpp
> -        Kalmar::ctx.releaseSignal(signal, signalIndex);
I believe this is not the right place to deallocate a single - instead this should occur in the HSACopy::dispose() routine.  The new profile mode is implemented inside the dispose routine and uses the timestamps from the signal so requires this change.

2017-06-21 03:17 UTC, bensander commented on lib/hsa/mcwamp_hsa.cpp
> +char * HCC_PROFILE_FILE=nullptr;
Yes - could be separate pull request?  these are environment variables which arguably are best as globals.  the file handle should be moved.

2017-06-21 03:42 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +char * HCC_PROFILE_FILE=nullptr;
ok to make them in another PR.

2017-06-21 03:42 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> -        Kalmar::ctx.releaseSignal(signal, signalIndex);
thanks for the clarification

2017-06-21 03:43 UTC, whchung approved these changes

2017-06-21 03:43 UTC, merged