[HIP Texture] The GPU virtual address for texture memory needs to be
RadeonOpenCompute/hcc pull request #411
Opened 2017-08-03 16:31 UTC by weixingzhang

aligned.

In this change, a bigger buffer will be allocated for alignment purpose
and _unalignedDevicePointer is added in struct AmPointerInfo for
original allocated address.

2017-08-04 15:19 UTC, whchung approved these changes
LGTM.

2017-08-04 19:07 UTC, whchung requested changes
@weixingzhang per inputs from @bensander and @scchan would you mind revise this PR so we retain existing `am_alloc` API, but add another `am_aligned_alloc` API?

2017-08-08 15:26 UTC, weixingzhang commented
The change is updated to reflect the feedback. Please review PR #415. Thanks!

2017-08-09 13:43 UTC, scchan commented
superseded by https://github.com/RadeonOpenCompute/hcc/pull/415

2017-08-09 13:43 UTC, closed without merging