HCC Runtime optimizations
RadeonOpenCompute/hcc pull request #432
Opened 2017-08-18 21:18 UTC by bensander

Collection of HCC runtime optimizations and improvements - see commit history for details.

Passes HIP dtests and tested in larger MI framework.

Not sure on failure to automatically merge?

2017-08-18 21:42 UTC, whchung commented
@bensander your branch doesn't seem to track the tip of HCC. could you rebase and submit once again?

2017-08-20 13:53 UTC, bensander commented
Done!

From: "Wen-Heng (Jack) Chung" <notifications@github.com>
Reply-To: RadeonOpenCompute/hcc <reply@reply.github.com>
Date: Friday, August 18, 2017 at 4:42 PM
To: RadeonOpenCompute/hcc <hcc@noreply.github.com>
Cc: Benjamin Sander <ben.sander@amd.com>, Mention <mention@noreply.github.com>
Subject: Re: [RadeonOpenCompute/hcc] HCC Runtime optimizations (#432)


@bensander<https://github.com/bensander> your branch doesn't seem to track the tip of HCC. could you rebase and submit once again?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/RadeonOpenCompute/hcc/pull/432#issuecomment-323467377>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ACYSArJenm8qdF9DnwFeUUDG9b-9Hvpkks5sZgU6gaJpZM4O8DhI>.

2017-08-22 03:19 UTC, bensander commented
@whchung can you review?

2017-08-24 18:46 UTC, scchan requested changes

2017-08-24 18:46 UTC, scchan commented on lib/hsa/mcwamp_hsa.cpp
> +                    foundFirstValidOp = false;
should set to "true" here?

2017-08-25 03:09 UTC, whchung requested changes

2017-08-25 03:09 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +            drainingQueue_ = true;
do we need a mutex here?

2017-08-25 03:09 UTC, whchung commented on lib/hsa/mcwamp_hsa.cpp
> +                    foundFirstValidOp = false;
this line indeed seems to be incorrect.

2017-08-25 06:16 UTC, bensander commented on lib/hsa/mcwamp_hsa.cpp
> +                    foundFirstValidOp = false;
Yep.  Pushed a fix.

2017-08-25 06:17 UTC, bensander commented on lib/hsa/mcwamp_hsa.cpp
> +            drainingQueue_ = true;
I believe HCC queues are inherently

2017-08-25 17:29 UTC, whchung approved these changes

2017-08-25 17:30 UTC, merged