Fix unit tests aarch64
RadeonOpenCompute/hcc pull request #524
Opened 2017-10-30 21:13 UTC by whchung

Tests changed in this PR would fail on Ubuntu on `aarch64`. After some study it appears `-m32` have detrimental effect on `aarch64` system and standard C++ headers can't be found. Remove them this PR.

This PR won't affect test result on `x86_64`.

2017-10-31 01:09 UTC, whchung commented
this PR should be taken after #522 .

2017-10-31 15:28 UTC, scchan approved these changes

2017-10-31 15:29 UTC, scchan requested changes
please resolve the conflict with clang

2017-10-31 15:43 UTC, whchung commented
@scchan fixed

2017-11-01 19:38 UTC, scchan commented
LGTM

2017-11-01 19:38 UTC, scchan approved these changes

2017-11-01 19:38 UTC, merged