Printf Add more supported types
RadeonOpenCompute/hcc pull request #681
Opened 2018-04-05 17:29 UTC by aaronenyeshi

Enable more types such as short and ulong by using types uint8_t, int8_t, uint16_t, int16_t, uint32_t, int32_t, uint64_t, int32_t. Also add more regular expression matching for short, long and long long types. Add testcase for these new supported types.

2018-04-05 17:31 UTC, aaronenyeshi commented
I am working on the half floating point type support.

2018-04-05 18:26 UTC, aaronenyeshi commented
New printf test is passing:
Testing Time: 551.32s
  Expected Passes    : 749
  Expected Failures  : 34
Built target test

2018-04-05 21:27 UTC, david-salinas approved these changes
LGTM

2018-04-05 21:57 UTC, whchung commented
@aaronenyeshi have we resolved thread safety issues within HCC runtime wrt printf? I'd like to hold off re-enabling printf until we make sure thread safety issues were resolved.

2018-04-05 22:11 UTC, scchan requested changes

2018-04-05 22:11 UTC, scchan commented on include/hc_printf.hpp
> +  void set(int16_t d)      [[hc,cpu]] { type = PRINTF_INT16_T;        data.s = d; }
We don't need sub-32bit int types for these since they'll be promoted to 32bit when passing to a varargs function

2018-04-05 22:11 UTC, scchan commented on include/hc_printf.hpp
> +static const std::regex unsignedInt64Pattern("(%){1}[-+#0]*[0-9]*((.)[0-9]+){0,1}(ll)([uoxX]){1}");
We don't need all these new regex patterns, we probably just need to add ([hl]*) to the existing signed/unsigned integer patterns

2018-04-05 22:11 UTC, scchan commented on include/hc_printf.hpp
> +      } else if (std::regex_search(specifier, specifierTypeMatch, unsignedIntegerPattern)) {
This needs to be revised after updating the regex patterns

2018-04-05 22:15 UTC, scchan commented
@whchung this PR is not about re-enabling printf, just adding support for more data types

2018-04-05 22:50 UTC, aaronenyeshi commented
Please find the changes to the data types, not more sub-32bit

2018-04-06 16:30 UTC, scchan approved these changes
LGTM

2018-04-06 17:32 UTC, aaronenyeshi commented
it seems Jenkins tests failing because it does not know how to evaluate branch names with slash (/):

```
[Pipeline] sh
[docker] Running shell script
+ docker build -t radeonopencompute/hcc/ashi1%2fprintf-add-types/hcc-lc-ubuntu-16.04:4 -f dockerfile-hcc-lc-ubuntu-16.04 .
invalid argument "radeonopencompute/hcc/ashi1%2fprintf-add-types/hcc-lc-ubuntu-16.04:4" for t: Error parsing reference: "radeonopencompute/hcc/ashi1%2fprintf-add-types/hcc-lc-ubuntu-16.04:4" is not a valid repository/tag: invalid reference format
See 'docker build --help'.
```

2018-04-06 18:12 UTC, merged