add git reference in GitSCM command for the submodules too
RadeonOpenCompute/hcc pull request #752
Opened 2018-06-08 20:05 UTC by david-salinas

We need the submodules class in the GitSCM command to also use the git reference.  The HCC Build/Test jobs are still timing out.

2018-06-18 20:03 UTC, scchan requested changes

2018-06-18 20:03 UTC, scchan commented on Jenkinsfile
> +      extensions: scm.extensions + [[$class: 'CloneOption', reference: '/var/gitcache/hcc.git'], [$class: 'CleanCheckout'], [$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: fa
Can we put the path into a variable?

2018-06-19 18:03 UTC, david-salinas commented on Jenkinsfile
> +      extensions: scm.extensions + [[$class: 'CloneOption', reference: '/var/gitcache/hcc.git'], [$class: 'CleanCheckout'], [$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: fa
Sure, let me do that now ...

2018-06-21 13:20 UTC, scchan approved these changes
LGTM

2018-06-21 13:20 UTC, merged