set failing tests as expected fails
RadeonOpenCompute/hcc pull request #774
Opened 2018-06-27 19:33 UTC by david-salinas

Adding XFAIL for the following tests, so they are counted as expected fails.

  HCC :: Unit/AMDGPU/register-control.cpp
    HCC :: Unit/AmpShortVectors/amp_short_vectors_2files.cpp
    HCC :: Unit/AmpShortVectors/amp_short_vectors_2files_1.cpp
    HCC :: Unit/Codegen/deser_def_body_compound_support_inheritclass.cpp

2018-06-28 20:26 UTC, scchan commented
I merged your PR for the register control attribute fix in clang, could you update this PR to remove register-control.cpp test?

2018-06-28 20:27 UTC, scchan requested changes
exclude register-control.cpp since the fix has been submitted to clang

2018-06-29 15:22 UTC, david-salinas commented
Ok, I've removed the register-control test from the known_fails, and remove XFAIL from the test source.

2018-06-29 18:19 UTC, scchan approved these changes

2018-06-29 18:19 UTC, merged