Add missing bitselect, bitinsert and bitextract funcs
RadeonOpenCompute/hcc pull request #841
Opened 2018-08-20 21:49 UTC by aaronenyeshi

2018-08-21 14:50 UTC, scchan requested changes
Could you add a unit test for these?  Thanks.

2018-08-23 19:21 UTC, scchan requested changes

2018-08-23 19:21 UTC, scchan commented on include/hc.hpp
> +  return (src2&31) == 0 ? 0 : (src0 << (32 - (src1&31) - (src2&31))) >> (32 - (src2&31));
can we add meaningful variables for src1&31 and src2&31 so that the algorithm is more understandable?  Same for 64-bit bitextract, bitinsert

2018-08-23 19:53 UTC, aaronenyeshi commented on include/hc.hpp
> +  return (src2&31) == 0 ? 0 : (src0 << (32 - (src1&31) - (src2&31))) >> (32 - (src2&31));
Thanks, just added it, also now the test for bitinsert_u64 works

2018-08-24 15:34 UTC, scchan approved these changes

2018-08-24 15:34 UTC, merged