-Werror ignoring return value of function
RadeonOpenCompute/hcc pull request #891
Opened 2018-10-06 16:07 UTC by Dekken

hcc/include/kalmar_aligned_alloc.h:30:5: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
    posix_memalign(&memptr, alignment, size);

2018-10-07 17:50 UTC, Dekken commented
oh weird!

2018-10-10 14:24 UTC, scchan requested changes

2018-10-10 14:24 UTC, scchan commented on include/kalmar_aligned_alloc.h
> +    (void) ignore;
I think we could put an assert to make sure the return value is zero and that should fix the problem

2018-10-10 14:26 UTC, PhilipDeegan commented on include/kalmar_aligned_alloc.h
> +    (void) ignore;
does that work for -DNDEBUG ?

2018-10-10 14:32 UTC, scchan commented on include/kalmar_aligned_alloc.h
> +    (void) ignore;
you are right, you'd still need `(void) ignore;` to make `-DNDEBUG` happy

2018-10-16 18:23 UTC, scchan approved these changes

2018-10-16 18:23 UTC, merged