Fixes for solving some application failure in dependent multiple threads usi…
RadeonOpenCompute/hcc pull request #973
Opened 2018-12-20 07:45 UTC by fronteer

The patch has two fixing points to solve issues occurred with multiple threads and multiple streams application. 

    1) The first issue occurs when Thread B calls hipStreamSynchronize() on stream A which just en-queued a Copy command and will en-queue a kernel by Thread A.

    The fix method here is to postpone the calling of "overridAcquireFenceIfNeeded" to a late point

    2) The second issue occurs when Thread B calls hipEventSynchronize() to wait on the completion of a Copy en-queued by Thread A on stream A, and the Event is created by hipEventDefaults, rather than hipEventReleaseToSystem.

    The fix method here is by absorbing the System Scope fencing request in HSABarrier::enqueueAsync().

2019-01-02 15:03 UTC, aaronenyeshi approved these changes
LGTM, thanks!

2019-01-16 19:35 UTC, scchan requested changes
Could you split this into 2 separate PRs, one for moving the `overrideAcquireFenceIfNeeded` and the other one for optimizing the memory scope?

2019-01-16 19:35 UTC, scchan commented on lib/hsa/mcwamp_hsa.cpp
> +        overrideAcquireFenceIfNeeded();
should be guarded by `HCC_OPT_FLUSH`

2019-01-16 19:35 UTC, scchan commented on lib/hsa/mcwamp_hsa.cpp
> +        overrideAcquireFenceIfNeeded();
should be guarded by `HCC_OPT_FLUSH`

2019-01-16 19:35 UTC, scchan commented on lib/hsa/mcwamp_hsa.cpp
> +         hsaQueue()->setNextSyncNeedsSysRelease(false);
Should be moved into the `if` branch above since it only needs to be set to `false` when the original value is `true`

2019-01-16 19:35 UTC, scchan commented on lib/hsa/mcwamp_hsa.cpp
> +         hsaQueue()->setNextKernelNeedsSysAcquire(false);
should be moved to inside the `if` branch above

2019-01-16 19:35 UTC, scchan commented on lib/hsa/mcwamp_hsa.cpp
>          hsaQueue()->releaseLockedRocrQueue();
Since you lock the rocr queue earlier in this function, could you remove the locking/unlocking of the queue within this scope?

2019-01-17 21:54 UTC, scchan commented
This PR has been superseded by 
https://github.com/RadeonOpenCompute/hcc/pull/991
https://github.com/RadeonOpenCompute/hcc/pull/992

2019-01-17 21:54 UTC, closed without merging